logging:
  level:
    com:
      alexm:
        bearspendings: debug
    org:
      springframework: info
      hibernate:
        type: info #trace - to see sql bind values
  file: import.log

com:
  alexm:
    bearspendings:
      imports:
        billsBatchSize: 10
        importPath: 'import'

spring:
  datasource:
    url: "jdbc:h2:file:~/.bear-spendings-data/db"
    username: sa
    password: manager
    driverClassName: org.h2.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
