logging:
  level:
    com:
      alexm:
        bearspendings: debug
    org:
      springframework: info
      hibernate:
        type: info #trace - to see sql bind values
  file: import-export/build/import.log

com:
  alexm:
    bearspendings:
      imports:
        billsBatchSize: 10
        importPath: 'import-export/build/import'

