logging:
  level:
    com:
      alexm:
        bearspendings: info
    org:
      springframework: info
      hibernate:
        type: info #trace - to see sql bind values
com:
  alexm:
    bearspendings:
      imports:
        billsbatchsize: 2
        importpath: 'build/import'
spring:
  datasource:
    url: "jdbc:h2:mem:bear-spendings-test-data"
    username: sa
    password: manager
    driverClassName: org.h2.Driver
  jpa:
    show_sql: true
  security:
    user:
      name: admin
      password: manager
