server:
  port: 8090

spring:
#  datasource:
#    url: "jdbc:sqlserver://localhost;databaseName=bearspendings"
#    username: sa
#    password: manager
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
